<?php

declare(strict_types=1);

namespace App\DataTables;

use DataTables\Table\Option\MainOption;
use DataTables\Table\Assets;
use DataTables\Table\Configure;


/**
 * Class AppDataTables
 */
class AppDataTables
{

	/**
	 * This will be applied to all DataTables tables.
	 *
	 * @param \DataTables\Table\Option\MainOption $options Options of DataTable library.
	 * @param \DataTables\Table\Assets $assets Options for asset load.
	 */
	public function mainConfig(MainOption $options, Assets $assets): void
	{

		$options->setStateSave(true);

		$assets->setEnabled(false);
	}

	/**
	 * This is the plugin configuration that will be applied to all DataTables tables.
	 * @param \DataTables\Table\Configure $configure Plugin base configurations.
	 */
	public function configure(Configure $configure): void
	{

		$configure->setColumnAutoGeneratedWarning(false);
	}
}
